// Test if the server is running
GET http://localhost:3001/

###

// List all the users currently in the database
GET http://localhost:3001/users

###

// Adds a user to the database
POST http://localhost:3001/users 
content-type: application/json

{
    "name": "JohnDoe",
    "email": "johndoe@flyingtoasters.com",
    "password": "123456"
}
