// VS code extension: REST Client
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Test if the server is running
GET http://localhost:3001/

###

// List all the matches currently in the database
GET http://localhost:3001/api/v1/matches

###

// List all matches by an event ID 
GET http://localhost:3001/api/v1/matches/1

###

// List match by ID 
GET http://localhost:3001/api/v1/match/1

###

// Adds a match to the database
POST http://localhost:3001/api/v1/match
content-type: application/json

{
    "matchNumber": "1",
    "blueScore": "1",
    "redScore": "1",
    "redOneTeamNumber": "3641",
    "redTwoTeamNumber": "10164",
    "redThreeTeamNumber": "9999",
    "blueOneTeamNumber": "1",
    "blueTwoTeamNumber": "2",
    "blueThreeTeamNumber": "3",
    "redRankingPoints": "1",
    "blueRankingPoints": "1",
    "matchKey": "2024iawesdd_qm1",
    "event_id": 1
}

###

// Adds a match to the database
DELETE http://localhost:3001/api/v1/match/2


